export const PhotoTypes = {
  GET_FIRST_ALBUM_SUCCESS: "GET_FIRST_ALBUM_SUCCESS",
  GET_FIRST_ALBUM_ERROR: "GET_FIRST_ALBUM_ERROR",

  GET_SECOND_ALBUM_SUCCESS: "GET_SECOND_ALBUM_SUCCESS",
  GET_SECOND_ALBUM_ERROR: "GET_SECOND_ALBUM_ERROR",

  GET_THIRD_ALBUM_SUCCESS: "GET_THIRD_ALBUM_SUCCESS",
  GET_THIRD_ALBUM_ERROR: "GET_THIRD_ALBUM_ERROR",

  GET_FOURTH_ALBUM_SUCCESS: "GET_FOURTH_ALBUM_SUCCESS",
  GET_FOURTH_ALBUM_ERROR: "GET_FOURTH_ALBUM_ERROR",

  GET_FIFTH_ALBUM_SUCCCESS: "GET_FIFTH_ALBUM_SUCCCESS",
  GET_FIFTH_ALBUM_ERROR: "GET_FIFTH_ALBUM_SUCCCESS",

  ADD_REMOVE_FAVORITES_SUCCESS: "ADD_REMOVE_FAVORITES_SUCCESS",

  CLEAR_STATE: "CLEAR_STATE",
};
